# Python in codecademy

## 1. Python Syntax

1. IndentationError: expected an indented block<br>
Properly indent the code with four spaces

2. Escaping characters<br>
'There\'s a snake in my boot!'

In [9]:
# A Single-Line Comment
monty = True
python = 1.234
monty_python = python**2
fifth_letter = "MONTY"[4]
print(fifth_letter)
pi = 3.14
print(str(pi))
print("pi is: %s" % (str(pi)))

Y
3.14
pi is: 3.14


## 2. String and Console Output

1. String Concatenation<br>
print "Spam "+"and "+"eggs"

2. Explicit String Conversion<br>
print "The value of pi is around " + str(3.14)

3. String Formatting with % <br>
print "Let's not go to %s. 'Tis a silly %s." % (string_1, string_2)<br>
Remember, we used the % operator to replace the %s placeholders with the variables in parentheses.

In [13]:
from datetime import datetime
now = datetime.now()
print(now)
print(now.year)
print(now.month)
print(now.day)
print('%s/%s/%s' % (now.year, now.month, now.day))
print('%s:%s:%s' % (now.hour, now.minute, now.second))

2017-01-08 14:54:48.229824
2017
1
8
2017/1/8
14:54:48


## 3. Conditionals & Control Flow

1. String Concatenation<br>
print "Spam "+"and "+"eggs"

2. Explicit String Conversion<br>
print "The value of pi is around " + str(3.14)

3. String Formatting with % <br>
print "Let's not go to %s. 'Tis a silly %s." % (string_1, string_2)<br>
Remember, we used the % operator to replace the %s placeholders with the variables in parentheses.


### Variable and Type (Object)

In [1]:
savings = 7000
year = 7
bmi = savings * year ** 7
print(type(year))
print(bmi)

<type 'int'>
5764801000


In [2]:
x = "hi"
type(x)

str

In [3]:
y = True
type(y)

bool

In [4]:
'ad'+'bc'

'adbc'

We can use add (+) only on the same types

In [5]:
money = 9999
#print("hi"+money)
print("hi" + str(money)) # for the same type

hi9999


### List

A list can include all different types including list itself 

In [6]:
li = [1.000, 2, "hello", True]

In [7]:
li2 = [[1, "one"], [2, "two"]]

In [8]:
print type(li)
print type(li2)

<type 'list'>
<type 'list'>


In [9]:
li = [1+2, "a"*5, 3] # "a"*5 
print(li)

[3, 'aaaaa', 3]


Slicing and dicing

In [10]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print a[0:3], a[:3]

[1, 2, 3] [1, 2, 3]


Changing list elements

In [11]:
fam = ["liz", 1.73, "emma", 1.68, "dad", 1.89]
fam[0:2] = ["lisa", 1.74] # both at once
fam

['lisa', 1.74, 'emma', 1.68, 'dad', 1.89]

Adding elements

In [12]:
fam_ext = fam + ["me", 1.79]
fam_ext

['lisa', 1.74, 'emma', 1.68, 'dad', 1.89, 'me', 1.79]

Delete elements from the list

In [13]:
del(fam[2])
fam

['lisa', 1.74, 1.68, 'dad', 1.89]

Behind the scences

In [14]:
x = ["a", "b", "c"]
y = x # Copy the reference, not the actual values themselves
y[1] = "z"
print "y:", y
print "x:", x # x and y have the same reference of a list

y: ['a', 'z', 'c']
x: ['a', 'z', 'c']


In [15]:
x = ["a", "b", "c"]
y = list(x)
y = x[:] # or here
y[1] = "z"
print "y:", y
print "x:", x

y: ['a', 'z', 'c']
x: ['a', 'b', 'c']


### Function

In [16]:
print round(1.68, 1)
print round(1.7)

1.7
2.0


In [17]:
help(round)
#?round

Help on built-in function round in module __builtin__:

round(...)
    round(number[, ndigits]) -> floating point number
    
    Round a number to a given precision in decimal digits (default 0 digits).
    This always returns a floating point number.  Precision may be negative.



### Methods

All variables (everything) in python are made by object.<br>
Object consists of str, float, list, and so on.<br>
Object have methods associated, depending on type/ <br>

Methods are functions that belong to objects.<br>
Lists, floats, integers and booleans are types that come packaged with a bunch of useful methods.

In [18]:
# list methods
li = [1,2,3,4,5,5,5,5,5]
print li.index(3)
print li.count(5)
li.append(7)
li.remove(3)
li.reverse()
li

2
5


[7, 5, 5, 5, 5, 5, 4, 2, 1]

In [19]:
# str methods
string = 'hello'
print string.capitalize()
print string.upper()
print string.replace('o','ooooooooooooo')
print string.count("l")

Hello
HELLO
hellooooooooooooo
2


### Packages

Functions and methods are poweful. But there are huge code in python. We will not use all of them and we have maintenance problem. That is why packages are coming. <br>

Packages.
* Directory of Python Scripts
* Each script = module
* The module specifies functions, methods and types
* Thousands of packages available 
  - Numpy, Matplotlib, Sciki-learn


In [20]:
import numpy
array([1, 2, 3])

NameError: name 'array' is not defined

In [ ]:
numpy.array([1, 2, 3])

In [ ]:
import numpy as np
np.array([1, 2, 3])

In [ ]:
from numpy import array # selective import
array([1, 2, 3])

from numpy import array is sometimes confusing when code is big. (Using Numpy, but not very clear). So, it is recommended to use import numpy as np in big code or if you want to show other people.

However,
General imports, like import math, make all functionality from the math package available to you. However, if you decide to only use a specific part of a package, you can always make your import more selective.

# Numpy

List Recap
* Powerful
* Collection of values
* Hold different types
* Change, add, remove

However, to analyze data, we often want to carry out operations over the entire collection values and we want to do fast. (Basic list of python can't do this)

In [21]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
bmi = weight / height ** 2 # they don't know how to calculate list

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

Solution: Numpy
* Numerical Python
* Alternative to Python List: Numpy Array
* Calculations over entire arrays
* Easy and fast


In [22]:
import numpy as np

height = [1.73, 1.68, 1.71, 1.89, 1.79]
np_height = np.array(height)

weight = [65.4, 59.2, 63.6, 88.4, 68.7]
np_weight = np.array(weight)

bmi = np_weight / np_height ** 2
bmi

array([ 21.85171573,  20.97505669,  21.75028214,  24.7473475 ,  21.44127836])

### Numpy: remarks

* Numpy arrays contain only one type
* When adding, distinguish between python_list and numpy_array

In [23]:
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])

In [24]:
python_list + python_list # Concatenate

[1, 2, 3, 1, 2, 3]

In [25]:
numpy_array + numpy_array # Calculation of add

array([2, 4, 6])

### Numpy Subsetting

In [26]:
bmi

array([ 21.85171573,  20.97505669,  21.75028214,  24.7473475 ,  21.44127836])

In [27]:
bmi[1]

20.975056689342409

In [28]:
bmi > 23 

array([False, False, False,  True, False], dtype=bool)

In [29]:
# Numpy Subsetting
bmi[bmi > 23]

array([ 24.7473475])

## 2D Numpy Arrays

ndarray type: N-dimenstional array

In [30]:
np_2d = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])

In [31]:
np_2d.shape

(2L, 3L)

In [32]:
print np_2d[0]
print np_2d[0][1]
print np_2d[0, 1]
print np_2d[:, 1:2]

[ 1.  2.  3.]
2.0
2.0
[[ 2.]
 [ 5.]]


## Numpy: Basic Statistics

Numpy also has basic functions like sum(), sort(), ... which are also included in basic python. <br>
However, the big difference is speed! (Enforce single data type!)



In [33]:
# Generate data
height = np.round(np.random.normal(1.75, 0.20, 5000), 2) # distr mean, distr std, # of sample
weight = np.round(np.random.normal(60.32, 15, 5000), 2)
np_city = np.column_stack((height, weight))

In [34]:
print np.mean(np_city[:,0])
print np.median(np_city[:,0])
print np.corrcoef(np_city[:,0], np_city[:,1])
print np.std(np_city[:,0])

1.74826
1.75
[[ 1.          0.02466371]
 [ 0.02466371  1.        ]]
0.200756101775
